// Точка входа handoff: упаковка материалов для клиента на базе docs/handoff.
//
// Копирует шаблон README + .env.example в каталог вывода и подставляет
// имя/порт/токен-плейсхолдер (без реального секрета).
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const version = "0.0.0-dev"

const helpText = `mvp-manager handoff — генерация материалов single-bot для клиента

Использование:
  handoff [-h|--help]
  handoff [-v|--version]
  handoff --out DIR [--name NAME] [--port PORT] [--token-placeholder STR]

Копирует шаблон из docs/handoff (или встроенный fallback) в DIR,
подставляя PORT / BOT_TOKEN-плейсхолдер / имя бота в README.

Примеры:
  handoff --out /tmp/client-bot --name acme-bot --port 18080
  handoff --out ./out --token-placeholder 'env:MY_BOT_TOKEN'
`

func main() {
	if len(os.Args) > 1 {
		switch os.Args[1] {
		case "-v", "--version", "version":
			fmt.Printf("handoff %s\n", version)
			return
		case "-h", "--help", "help":
			fmt.Print(helpText)
			return
		}
	}

	outDir := ""
	name := "client-bot"
	port := "18080"
	tokenPH := "replace-me"

	for i := 1; i < len(os.Args); i++ {
		a := os.Args[i]
		need := func(flag string) string {
			if i+1 >= len(os.Args) {
				fatal("%s требует значение", flag)
			}
			i++
			return os.Args[i]
		}
		switch a {
		case "--out", "-o":
			outDir = need(a)
		case "--name":
			name = need(a)
		case "--port":
			port = need(a)
		case "--token-placeholder", "--token":
			tokenPH = need(a)
		default:
			fatal("неизвестный аргумент %q", a)
		}
	}
	if outDir == "" {
		fatal("--out обязателен")
	}

	tplDir := findTemplateDir()
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fatal("mkdir %s: %v", outDir, err)
	}

	envSrc := filepath.Join(tplDir, ".env.example")
	envBody, err := os.ReadFile(envSrc)
	if err != nil {
		envBody = []byte(fallbackEnvExample)
	}
	envOut := substituteEnv(string(envBody), port, tokenPH)
	envPath := filepath.Join(outDir, ".env.example")
	if err := os.WriteFile(envPath, []byte(envOut), 0o644); err != nil {
		fatal("write %s: %v", envPath, err)
	}

	readmeSrc := filepath.Join(tplDir, "README.md")
	readmeBody, err := os.ReadFile(readmeSrc)
	if err != nil {
		readmeBody = []byte(fallbackReadme)
	}
	readmeOut := substituteReadme(string(readmeBody), name, port, tokenPH)
	readmePath := filepath.Join(outDir, "README.md")
	if err := os.WriteFile(readmePath, []byte(readmeOut), 0o644); err != nil {
		fatal("write %s: %v", readmePath, err)
	}

	// Короткий launch-contract reminder.
	metaPath := filepath.Join(outDir, "HANDOFF.txt")
	meta := fmt.Sprintf(
		"handoff generated by mvp-manager\nbot_name=%s\nport=%s\ntoken_placeholder=%s\nsource_template=%s\n",
		name, port, tokenPH, tplDir,
	)
	if err := os.WriteFile(metaPath, []byte(meta), 0o644); err != nil {
		fatal("write %s: %v", metaPath, err)
	}

	fmt.Printf("handoff written to %s\n", outDir)
	fmt.Printf("  %s\n  %s\n  %s\n", envPath, readmePath, metaPath)
}

func findTemplateDir() string {
	// Ищем docs/handoff относительно cwd и относительно бинарника.
	candidates := []string{
		"docs/handoff",
		filepath.Join("..", "docs", "handoff"),
	}
	if exe, err := os.Executable(); err == nil {
		candidates = append(candidates,
			filepath.Join(filepath.Dir(exe), "..", "docs", "handoff"),
			filepath.Join(filepath.Dir(exe), "docs", "handoff"),
		)
	}
	for _, c := range candidates {
		if st, err := os.Stat(c); err == nil && st.IsDir() {
			abs, _ := filepath.Abs(c)
			return abs
		}
	}
	return "docs/handoff" // fallback path for messages
}

func substituteEnv(body, port, tokenPH string) string {
	lines := strings.Split(body, "\n")
	for i, line := range lines {
		trim := strings.TrimSpace(line)
		if strings.HasPrefix(trim, "PORT=") {
			lines[i] = "PORT=" + port
		}
		if strings.HasPrefix(trim, "BOT_TOKEN=") {
			lines[i] = "BOT_TOKEN=" + tokenPH
		}
	}
	return strings.Join(lines, "\n")
}

func substituteReadme(body, name, port, tokenPH string) string {
	out := body
	// Добавляем блок с параметрами в конец, не ломая исходный шаблон.
	extra := fmt.Sprintf(`

---

## Параметры этой выдачи

| Параметр | Значение |
|---|---|
| bot name | %s |
| PORT | %s |
| BOT_TOKEN placeholder | %s |

Сгенерировано `+"`mvp-manager handoff`"+`.
`, name, port, tokenPH)
	return out + extra
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "handoff: "+format+"\n", args...)
	os.Exit(1)
}

const fallbackEnvExample = `# Launch contract (ТЗ §9)
PORT=18080
BOT_TOKEN=replace-me
BOT_MODE=webhook
CHANNEL=telegram
`

const fallbackReadme = `# Handoff: single-bot

Скопируйте .env.example → .env, задайте BOT_TOKEN и PORT, запустите бота.
`
